version: '3'
services:
  postgresql:
    image: postgres
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    volumes:
      - ./tmp/mongodb:/var/lib/mongodb/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/brainpin
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - mongodb